apiVersion: v1
kind: PersistentVolume
metadata:
  name: ss-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/stateful-demo
