apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  labels:
    app: nfs
spec:
  containers:
  - name: nfs
    image: k8s.gcr.io/volume-nfs:0.8
    securityContext:
      privileged: true
    ports:
    - containerPort: 2049
      name: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  selector:
    app: nfs
  ports:
  - name: nfs
    port: 2049
    targetPort: 2049
