apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-test-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  # storageClassName: csi-demo   <-- uncomment and replace with a real CSI storage class in your cluster
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-test-app
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo hello > /data/out && sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: csi-test-pvc
