apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: stateapp
  serviceName: "stateapp-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: stateapp
    spec:
      containers:
      - name: app
        image: busybox
        command: ["sh", "-c", "while true; do echo 'hello' > /data/msg; sleep 10; done"]
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
